version:            V016--10-Aug-2020
title:              Rahmat M. Samik-Ibrahim
# email:              my-e@ma.il
description:        Hello, this is Rahmat M. Samik-Ibrahim!
author:             Rahmat M. Samik-Ibrahim
# baseurl:            "/rahmat"
url:                "https://rahmat.vlsm.org"

# Social Profiles
twitter_username:   rms46
github_username:    rms46
google_analytics: UA-89852122-6

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

