version:            V025a--20-Jun-2022
title:              Rahmat M. Samik-Ibrahim
# email:              my-e@ma.il
description:        vlsm.org (pronounced VauLSMorg) is just<br>a domain, a whole domain, and nothing but a domain!<br>This is the WAY!
author:             Rahmat M. Samik-Ibrahim
# baseurl:            "/rahmat"
url:                "https://rahmat.vlsm.org/"

# Social Profiles
github_username:    rms46
google_analytics:   G-F91XYGVGJ7

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

