version:            V023a--04-May-2022
title:              Rahmat M. Samik-Ibrahim
# email:              my-e@ma.il
description:        Nama saya Rahmat, Rahmat nama saya.<br>Kalau bukan Rahmat, bukan nama saya!
author:             Rahmat M. Samik-Ibrahim
# baseurl:            "/rahmat"
url:                "https://rahmat.vlsm.org/"

# Social Profiles
github_username:    rms46
google_analytics: UA-89852122-6

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

